version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5019:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  db:
    image: nouchka/sqlite3
    volumes:
      - ./backend/tasks.db:/data/tasks.db

